version: "3"

services:
  web:
    container_name: c2_web
    build:
      context: ./nginx
      args:
        - ACCOUNT_ID=${ACCOUNT_ID}
        - LATEST=latest
      dockerfile: Dockerfile
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
      - ssl_data:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - data
  app:
    container_name: c2_app
    build:
      context: ./app
      dockerfile: Dockerfile
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - ./app:/app
    ports:
      - 3000:3000
    command: yarn dev
    restart: always
    depends_on:
      - web
  data:
    container_name: c2_data
    build:
      context: ./data
      args:
        - ENV=dev
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      # Docker イメージ間でデータを共有するために同じように記載
      # Docker コマンドの --volumes-from と同じ動作
      - ssl_data:/etc/nginx/ssl

volumes:
  # 各 Docker イメージでデータを共有するための設定
  ssl_data:
